config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  devise_for :users
root "welcome#index"
get "admin" => 'admin#index'
namespace :admin do
  resources :categories
  resources :products
  resources :orders
end
scope '(:locale)' do
  resources :orders
  resources :line_items
  resources :carts
end
resources :categories, only: [:index, :show] do
  resources :products, only: [:index, :show]
end
resources :users do
  resources :orders, only: [:new, :create, :index, :show]
end

end

app/models/order.rb
class Order < ActiveRecord::Base
	PAYMENT_TYPES = [ "Check", "Credit card", "Purchase order" ]
  belongs_to :user
  has_many :line_items, dependent: :destroy
  validates :pay_type, inclusion: PAYMENT_TYPES
  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end

  def total_price
    line_items.inject(0) { |sum, item| sum + item.total_price }
  end

  STATUS = [
    [ "New", :new ],
    [ "Pending", :pending],
    [ "Approved", :dispatched ],
    [ "Cancelled", :cancelled]
  ]
end

app/controllers/admin/orders_controller.rb
module Admin
  class OrdersController < AdminController
    include CurrentCart
    before_action :set_cart, only: [:new, :create]
    before_action :set_order, only: [:show, :edit, :update, :destroy]

    # GET /orders
    # GET /orders.json
    def index
      @orders = Order.all
    end

    # GET /orders/1
    # GET /orders/1.json
    def show
      respond_to do |format|
        format.html
        format.pdf do
          pdf = OrderPdf.new(@order)
          send_data pdf.render, filename: "order_#{@order.id}.pdf",
                                type: "application/pdf",
                                disposition: "inline"
        end
      end
    end

    # GET /orders/new
    def new
      if @cart.line_items.empty?
        redirect_to root_path, notice: "Your cart is empty"
        return
      end

      @order = Order.new
    end

    # GET /orders/1/edit
    def edit
    end

    # POST /orders
    # POST /orders.json
    def create
      @order = Order.new(order_params)
      @order.add_line_items_from_cart(@cart)
      respond_to do |format|
        if @order.save
          Cart.destroy(session[:cart_id])
          session[:cart_id] = nil
          format.html { redirect_to root_path, notice: 'Thank you for your order.' }
          format.json { render :show, status: :created, location: @order }
        else
          format.html { render :new }
          format.json { render json: @order.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /orders/1
    # PATCH/PUT /orders/1.json
    def update
      respond_to do |format|
        if @order.update(order_params)
          format.html { redirect_to @order, notice: 'Order was successfully updated.' }
          format.json { render :show, status: :ok, location: @order }
        else
          format.html { render :edit }
          format.json { render json: @order.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /orders/1
    # DELETE /orders/1.json
    def destroy
      @order.destroy
      respond_to do |format|
        format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_order
        @order = Order.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def order_params
        params.require(:order).permit(:pay_type, :user_id)
      end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:new, :create]
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_filter :authorize_user, :only => [:show]

  # GET /orders
  # GET /orders.json
  def index
     @orders = current_user.orders
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    respond_to do |format|
      format.html
      format.pdf do
        pdf = OrderPdf.new(@order)
        send_data pdf.render, filename: "order_#{@order.id}.pdf",
                              type: "application/pdf",
                              disposition: "inline"
      end
    end
  end

  # GET /orders/new
  def new
    if @cart.line_items.empty?
      redirect_to root_path, notice: "Your cart is empty"
      ConfirmationMailer.confirmation_email(@order.user).deliver_now
      return
    end

    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.add_line_items_from_cart(@cart)
    respond_to do |format|
      if @order.save
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil
        format.html { redirect_to root_path, notice: 'Thank you for your order.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_update_params)
        format.html { redirect_to admin_order_path, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:pay_type, :user_id)
    end
    def authorize_user
      unless current_user.eql?(@order.user)
      flash[:notice]="You are not authorized to access this order"
      redirect_to orders_path 
      end
    end
    def order_update_params
      params.require(:order).permit(:status)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/_form.html.erb
<%= simple_form_for(@order) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.label :pay_type %>
    <%= f.select :pay_type, Order::PAYMENT_TYPES %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/admin/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orders</h1>

<table>
  <thead>
    <tr>
      <th>Pay type</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.pay_type %></td>
        <td><%= order.user_id %></td>
        <td><%= order.total_price %></td>
        <td><%= link_to 'Show', admin_order_path(order) %></td>
        <td><%= link_to 'Edit', admin_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= form_for([@admin,order]) do |f| %>
        <%= f.select :status, Order::STATUS %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

<script>
  $(function(){
    $("form select").on("change",function(){
      $(this).parent("form").submit();
    });
  })
</script>

app/views/admin/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/admin/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pay type:</strong>
  <%= @order.pay_type %>
</p>

<p>
  <strong>User:</strong>
  <%= @order.user %>
</p>

<p>
	<strong>Products:</strong>
  <p>Product Quantity Unit Price Full Price</p>
	<% @order.line_items.each do |item| %>
		<p><%= item.product.name %> <%= item.quantity %> <%=item.product.price%> <%=item.total_price %></p>
	<% end %>
</p>

<p>
  <strong>Total Price:</strong>
  <%= @order.total_price %>
</p>

<%= link_to 'Edit', edit_admin_order_path(@order) %> |
<%= link_to 'Back', admin_orders_path %> |
<%= link_to "Download Invoice (PDF)", admin_order_path(@order, format: "pdf")%>