config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  devise_for :users
root "welcome#index"
get "admin" => 'admin#index'
namespace :admin do
  resources :categories
  resources :products
  resources :orders
end
scope '(:locale)' do
  resources :orders
  resources :line_items
  resources :carts
end
resources :categories, only: [:index, :show] do
  resources :products, only: [:index, :show]
end
resources :users do
  resources :orders, only: [:new, :create, :index, :show]
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
	def number_to_euro(amount)
	  number_to_currency(amount,:unit=>'€')
	end
	def itemsnumber
  		current_user.cart.line_items.count
  	end
  def cartpage
  	if @cart 
  		return @cart
  	else
  		return current_user.cart
  	end
  end

  def categ
    @category = Category.find(params[:search])
  end
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end
end

app/views/application/_cart.html.erb
<% if @cart.line_items %>
	<p class="navbar-text.navbar-right">
		<% if @cart.line_items.count==0 %>
			<li><%= link_to "Your cart is empty"%></li>
		<%else%>
			<li><%= link_to "You have #{pluralize @cart.line_items.count, "item"}.", cart_path%></li>
		<%end%></p>
<%end%>


app/views/application/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">My Basic Store</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= form_tag(category_products_path(@category), :method => "get", id: "search-form", class: "navbar-form navbar-left") do %>
        <div class="form-group">
        <%= text_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>
        </div>
        <%= submit_tag "Search", :class => 'btn btn-default',:name => nil%>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Categories and Products", categories_path%></li>
        <li><%= link_to "You have #{itemsnumber} items in your cart", cart_path(cartpage)%></li>
        <% if user_signed_in? %>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li><%= link_to "My orders", user_orders_path(current_user) %></li>
              <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="active"><li><%= link_to "Login", new_user_session_path%></li>
        <%end%>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>